# Generated by Django 5.1.4 on 2025-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_quizzes',
            field=models.ManyToManyField(related_name='completed_by', through='quizes.Results', to='quizes.quiz', verbose_name='completed_quizzes'),
        ),
    ]
