# Generated by Django 5.1.4 on 2025-01-13 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('visibleId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='visibleId')),
                ('text', models.CharField(max_length=1275, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('visibleId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='visibleId')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=180, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quizes/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('visibleId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='visibleId')),
                ('data', models.JSONField(default=dict, verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('visibleId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='visibleId')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('visibleId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='visibleId')),
                ('text', models.CharField(max_length=275, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='image')),
                ('isCorrect', models.BooleanField(default=False, verbose_name='isCorrect')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizes.question')),
            ],
        ),
    ]
