# Generated by Django 5.1.4 on 2025-01-13 20:08

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('visibleId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='visibleId')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
            ],
        ),
    ]
