# Generated by Django 5.1.4 on 2025-01-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='quizes.material', verbose_name='material'),
        ),
    ]
