# Generated by Django 5.1.4 on 2025-01-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_alter_quiz_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizes.material', verbose_name='material'),
        ),
    ]
